# Generated by Django 4.1 on 2022-10-11 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İsim - Soyisim')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Takı Miktarı')),
                ('jewelry_kind', models.CharField(max_length=20, verbose_name='Takı Türü')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
            ],
            options={
                'db_table': 'Takılar',
            },
        ),
    ]
