# Generated by Django 4.1 on 2022-10-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='jewelry_kind',
            field=models.CharField(default=1, max_length=20, verbose_name='Takı Türü'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Takı Miktarı'),
        ),
    ]
