# Generated by Django 4.1 on 2022-10-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0002_jewelry_jewelry_kind_alter_jewelry_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Takı Miktarı'),
        ),
        migrations.AlterModelTable(
            name='jewelry',
            table='Takılar',
        ),
    ]
