# Generated by Django 4.1 on 2022-10-11 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jewelry_app', '0003_alter_jewelry_price_alter_jewelry_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Authorized'),
            preserve_default=False,
        ),
    ]
